#!/bin/bash

# 
#  Copyright 2025 Sifiso Fakude
# 
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# 

# Default minimum Android SDK
MIN_SDK=23

# Default target Android SDK
TARGET_SDK=36

# Default compile Android SDK
COMPILE_SDK=36

# Root directory for projects, uncomment variable to set a value
# eg. PROJECT_DIR=/home/user/AndroidProjects
PROJECT_DIR=""

# Path to the android sdk to compile projects
# eg. ANDROID_SDK=$HOME/Android/SDK
ANDROID_SDK=""

# Path to the NDK to compile C/C++ shared libraries
# eg. ANDROID_SDK=$HOME/Android/NDK
# ANDROID_NDK=$ANROID_NDK_HOME
